paths:
  jquery: 'jquery'
  underscore: 'underscore'
  jquery-spin: 'plugins/jquery/jquery.spin'
  spin: 'plugins/jquery/spin'
  # ghosttype: 'plugins/jquery/jquery.ghosttype-1.2'
  waypoints: 'plugins/jquery/waypoints'
  waypoints-sticky: 'plugins/jquery/waypoints-sticky'

shim:
  'jquery':
    exports: '$'
  'underscore':
    exports: '_'
  'jquery-spin':
    deps: ['jquery', 'spin']
  # 'ghosttype':
  #   deps: ['jquery']
  'waypoints':
    deps: ['jquery']
  'waypoints-sticky':
    deps: ['jquery']